Tasks modul 3
js-tasks-ru/vue-20230516_daniil-maltsev pull request #7
Opened 2023-06-06 15:23 UTC by DAMaltsev

2023-06-06 15:24 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-06-06 15:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-06-06 23:48 UTC, ShGKme requested changes
В `02-components/01-CounterButtonComponent` требуется добавить описание событий компонента.

2023-06-06 23:48 UTC, ShGKme commented on 02-components/03-MeetupCover/components/MeetupCover.js
> +  },
Это свойство не используется

2023-06-06 23:48 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button @click="$emit('update:count', count + 1 )" type="button">{{count}}</button>`,
Хотя компонент работает без этого, все события крайне желательно описывать в опции `emits`.
Иначе теряется документирование компонента, поддержка IDE, а для событий с названиями, совпадающими с DOM событиями, будет дублирование.

2023-06-09 03:24 UTC, DAMaltsev commented on 02-components/03-MeetupCover/components/MeetupCover.js
> +  },
Убрал

2023-06-09 03:24 UTC, DAMaltsev commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button @click="$emit('update:count', count + 1 )" type="button">{{count}}</button>`,
Добавил -  emit: ['update:count'], Этого достаточно или нужно еще метод сделать?

2023-06-09 03:56 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-06-09 10:01 UTC, ShGKme approved these changes
Все задачи приняты

2023-06-09 10:02 UTC, merged